name: sammba
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - ipython
  - nipype>=1.0.4
  - nilearn>=0.4.0
  - numpy>=1.14
  - scipy>=0.19
  - nibabel>=2.0.2
  - scikit-learn>=0.19
  - matplotlib>=1.5.1
  - nose>=1.2.1
  - pip
  - pip:
      - doctest-ignore-unicode
