name: Test docker file

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v6      # buduj i ładuj obraz lokalnie :contentReference[oaicite:1]{index=1}
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: user/app:test

      - name: Run container smoke-test
        run: |
          docker run --rm user/app:test echo "OK" 
